### ISSUE TITLE
Unable to build on MacOS

### ISSUE THREAD

**Issue by agreenbhm** [canokeys/canokey-qemu#1]
I'm using MacOS 13.3, attempting to build this module.  I've tried building with both Clang and GCC (10 and 13) but get the same error no matter what.  I'm able to build on Linux without issue.  I've exhausted my troubleshooting abilities as I'm not really familiar with CMake.  Any ideas how this can be successfully built on MacOS?

```
[ 96%] Linking C static library libcanokey-core.a
[ 96%] Built target canokey-core
[ 97%] Building C object CMakeFiles/canokey-qemu.dir/canokey-core/virt-card/fabrication.c.o
[ 98%] Building C object CMakeFiles/canokey-qemu.dir/Src/qemu.c.o
[ 98%] Building C object CMakeFiles/canokey-qemu.dir/canokey-core/virt-card/device-sim.c.o
[ 98%] Building C object CMakeFiles/canokey-qemu.dir/canokey-core/littlefs/bd/lfs_filebd.c.o
[100%] Linking C shared library libcanokey-qemu.dylib
Undefined symbols for architecture x86_64:
  "_canokey_emu_get_rx_data_size", referenced from:
      _USBD_LL_GetRxDataSize in qemu.c.o
  "_canokey_emu_prepare_receive", referenced from:
      _USBD_LL_PrepareReceive in qemu.c.o
  "_canokey_emu_set_address", referenced from:
      _USBD_LL_SetUSBAddress in qemu.c.o
  "_canokey_emu_stall_ep", referenced from:
      _USBD_LL_StallEP in qemu.c.o
  "_canokey_emu_transmit", referenced from:
      _USBD_LL_Transmit in qemu.c.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [libcanokey-qemu.0.dylib] Error 1
make[1]: *** [CMakeFiles/canokey-qemu.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ZenithalHourlyRate** [comment]
```
canokey_emu_get_rx_data_size
```

libcanokey-qemu expects these symbols from qemu. But it seems that MacOS compiler treat them like internal symbol. I do not use MacOS so I do not know how to handle it.

https://github.com/pgRouting/pgrouting/issues/5

Maybe we need to change `SHARED` into `MODULE` and add QEMU as the bundle_loader?

One thing that can make trouble is that now this is circular dependencies: qemu use symbols from libcanokey-qemu and libcanokey-qemu use symbols from qemu. I have no idea on this.

**Comment by ZenithalHourlyRate** [comment]
Other materials I found

* https://github.com/ziglang/zig/issues/8180
* https://blog.tim-smith.us/2015/09/python-extension-modules-os-x/

A friend suggested using static lib. I am not against it. Seems like changing the SHARED flag and corresponding pkg-config should work.

**Comment by agreenbhm** [comment]
Thanks for the feedback.  Besides changing the SHARED flag to STATIC, how does pkg-config need to be modified?  I was able to build the dylib for SHARED using the "-undefined dynamic_lookup" flag, but now I'm running into the circular reference I think you were alluding to (qemu.c from canokey-qemu is referencing a symbol from qemu itself).

**Comment by ZenithalHourlyRate** [comment]
Removing 

https://github.com/canokeys/canokey-qemu/blob/b70af31229f1858089c3366f71b8d771de4a1e84/canokey-qemu.pc.in#L7

should work?

**Comment by agreenbhm** [comment]
Finally figured it out.  Thanks for the help; I had to make a few tweaks but eventually this is what made it work:

1. Change from SHARED to STATIC https://github.com/canokeys/canokey-qemu/blob/b70af31229f1858089c3366f71b8d771de4a1e84/CMakeLists.txt#L26 

2. Copy ALL static libraries compiled by canokey-qemu (should be 4: libcanokey-qemu.a, libcanokey-crypto.a, ibmbedcrypto.a, libcanokey-core.a) to a central directory.  I made my own include folder, but you could just copy them to /usr/local/lib.  Let's assume it's /usr/local/lib.  I found the files by running (from the root of the canokey-qemu repo folder) 'find ./ -name "*.a"'.

3. Run the QEMU configure script with a few extra flags: ./configure --enable-canokey --enable-cocoa --extra-cflags='-Wno-unused-but-set-variable' --extra-ldflags='-L/usr/local/lib -lcanokey-qemu  -lcanokey-core -lmbedcrypto -lcanokey-crypto'

"--enable-cocoa" makes the QEMU gui work on Mac, "--extra-ldflags" is what's needed to include the static libraries that we copied to /usr/local/lib in step 2, "--extra-cflags" is to ignore an error that's thrown during compilation; this might not be necessary if using gcc <=12 (which I did, after giving up on clang).

Doing this I was able to build QEMU 8.0.0 from trunk and launch a VM successfully with a virtual Canokey attached!

Thanks so much for your help @ZenithalHourlyRate!

**Comment by ZenithalHourlyRate** [comment]
If you get the time, could you make such changes to the repo so that other users could benefit from it? Seems that the `/usr/local/lib` trick is not disired by most people, I think that could be resolved by pkg-config, as qemu finds where libcanokey-qemu is by pkg-config, and these cflags like `-L/usr/local/lib` are not needed.

**Comment by agreenbhm** [comment]
> If you get the time, could you make such changes to the repo so that other users could benefit from it? Seems that the `/usr/local/lib` trick is not disired by most people, I think that could be resolved by pkg-config, as qemu finds where libcanokey-qemu is by pkg-config, and these cflags like `-L/usr/local/lib` are not needed.

PR submitted.
